
services:

  postgres:
    image: postgres:16
    container_name: thaibox-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: thaibox-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: backend/TKThaiBox.API/Dockerfile
    container_name: thaibox-api
    depends_on:
      - postgres
    environment:
      ConnectionStrings__Default: Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "5000:8080"

  frontend:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile
    container_name: thaibox-frontend
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  postgres_data: